@startuml

  clientA -> Server: message(username, body, handshake=true)

  clientA <- Server: message(username="Server", body="novo usuário conectado")

  clientB <- Server: message(username="Server", body="novo usuário conectado")



  clientB -> Server: message(username, body, handshake=true)

  clientB <- Server: message(username="Server", body="novo usuário conectado")

  clientA <- Server: message(username="Server", body="novo usuário conectado")



  clientA -> Server: message(username, body="Oi tudo bem?")

  clientA <- Server: message(username, body="Oi tudo bem?")

  clientB <- Server: message(username, body="Oi tudo bem?")



  clientB -> Server: message(username, body="tudo bem")

  clientB <- Server: message(username, body="tudo bem")

  clientA <- Server: message(username, body="Oi tudo bem?")

@enduml